global using static Domain.Exceptions.CustomArgumentNullException;
global using Domain.Entities;
global using Domain.Errors;
global using Domain.Repositories;
global using Domain.Shared;
global using Application.Abstractions;
global using Application.Abstractions.Messaging;
global using Domain.ValueObjects;
global using Mapster;
global using Domain.Enums;
global using FluentValidation;